### PR TITLE
CB-51 API: FileTransfer - Support PUT Method

### PR DESCRIPTION
**Pull request by daserge**
Adds PUT method handling to `upload` endpoint.
Replaces tabs with whitespaces.

[Jira issue](https://issues.apache.org/jira/browse/CB-51)

### CODE REVIEW

**Comment by daserge** [comment]
@shazron, could you please take a look? 
This is required for https://github.com/apache/cordova-plugin-file-transfer/pull/108

**Comment by shazron** [comment]
I'm on it.

**Comment by shazron** [comment]
Nodejitsu updated

**Comment by daserge** [comment]
Thank you guys!

**Pull request merged**
