### PR TITLE
CB-10974 Cordova file transfer Content-Length header problem

### PR DESCRIPTION
**Pull request by daserge**
Adds headers echo endpoint

[Jira issue](https://issues.apache.org/jira/browse/CB-10974)

### CODE REVIEW

**Comment by daserge** [comment]
Merged in https://github.com/apache/cordova-labs/commit/b10c5dbe731a30eb4f5af93631684eccd18c45f4

**Comment by daserge** [comment]
@riknoll, could you please update the server so that https://github.com/apache/cordova-plugin-file-transfer/pull/141 could be merged?

**Comment by riknoll** [comment]
@daserge sorry for the delay, I am verifying something and then will do the deploy ASAP

**Comment by daserge** [comment]
@riknoll, I'm friendly remaining regarding the server update...

**Comment by riknoll** [comment]
@daserge I haven't forgotten! The issue is that some changes were recently made to the server configuration and the README appears to be out of date. I'm trying to verify the correct steps with those involved to make sure I'm complying with Infra's policies. Sorry for the delay!

**Comment by riknoll** [comment]
@daserge issue is resolved and server should be updated! Let me know if it isn't!

**Comment by daserge** [comment]
@riknoll, thanks a lot!

**Pull request closed without merging**
